#ifndef ESP32_SERVER_DASHBOARD_ITEM_TYPE_H
#define ESP32_SERVER_DASHBOARD_ITEM_TYPE_H

enum DASHBOARD_ITEM_TYPE
{
    DASHBOARD_ITEM_TYPE_NONE = 0,
    // CPU
    DASHBOARD_ITEM_TYPE_CPU_LOAD = 1,
    DASHBOARD_ITEM_TYPE_CPU_USER = 2,
    DASHBOARD_ITEM_TYPE_CPU_SYSTEM = 3,
    DASHBOARD_ITEM_TYPE_CPU_IDLE = 4,
    DASHBOARD_ITEM_TYPE_CPU_ACTIVE = 5,
    DASHBOARD_ITEM_TYPE_CPU_NICE = 6,
    DASHBOARD_ITEM_TYPE_CPU_IOWAIT = 7,
    DASHBOARD_ITEM_TYPE_CPU_SOFT_IRQ = 8,
    DASHBOARD_ITEM_TYPE_CPU_STEAL = 9,
    DASHBOARD_ITEM_TYPE_CPU_GUEST = 10,
    DASHBOARD_ITEM_TYPE_CPU_GUEST_NICE = 11,
    // MEMORY
    DASHBOARD_ITEM_TYPE_MEM_ACTIVE = 12,
    DASHBOARD_ITEM_TYPE_MEM_AVAILABLE = 13,
    DASHBOARD_ITEM_TYPE_MEM_BUFFERED = 14,
    DASHBOARD_ITEM_TYPE_MEM_CACHED = 15,
    DASHBOARD_ITEM_TYPE_MEM_DIRTY = 16,
    DASHBOARD_ITEM_TYPE_MEM_FREE = 17,
    DASHBOARD_ITEM_TYPE_MEM_INACTIVE = 18,
    DASHBOARD_ITEM_TYPE_MEM_LAUNDRY = 19,
    DASHBOARD_ITEM_TYPE_MEM_MAPPED = 20,
    DASHBOARD_ITEM_TYPE_MEM_SHARED = 21,
    DASHBOARD_ITEM_TYPE_MEM_SWAP_CACHED = 22,
    DASHBOARD_ITEM_TYPE_MEM_SWAP_FREE = 23,
    DASHBOARD_ITEM_TYPE_MEM_USED = 24,
    // CPU TEMPERATURE
    DASHBOARD_ITEM_TYPE_CPU_TEMPERATURE = 25,
    // NETWORKING
    DASHBOARD_ITEM_TYPE_NETWORK_INTERFACE_DOWNLOAD_BANDWIDTH = 26,
    DASHBOARD_ITEM_TYPE_NETWORK_INTERFACE_UPLOAD_BANDWIDTH = 27,
    DASHBOARD_ITEM_TYPE_NETWORK_INTERFACE_DOWNLOAD_DYNAMIC_BANDWIDTH = 28,
    DASHBOARD_ITEM_TYPE_NETWORK_INTERFACE_UPLOAD_DYNAMIC_BANDWIDTH = 29,
};

#endif // ESP32_SERVER_DASHBOARD_ITEM_TYPE_H
