#ifndef ESP32_SERVER_DASHBOARD_ITEM_TYPE_H
#define ESP32_SERVER_DASHBOARD_ITEM_TYPE_H

#define MAX_DASHBOARDS 3
#define DASHBOARD_ITEM_COUNT 5

enum DASHBOARD_ITEM_TYPE
{
    DASHBOARD_ITEM_TYPE_NONE = 0,
    // CPU
    DASHBOARD_ITEM_TYPE_CPU_LOAD = 1,
    DASHBOARD_ITEM_TYPE_CPU_USER = 2,
    DASHBOARD_ITEM_TYPE_CPU_SYSTEM = 3,
    DASHBOARD_ITEM_TYPE_CPU_IDLE = 4,
    DASHBOARD_ITEM_TYPE_CPU_ACTIVE = 5,
    DASHBOARD_ITEM_TYPE_CPU_NICE = 6,
    DASHBOARD_ITEM_TYPE_CPU_IOWAIT = 7,
    DASHBOARD_ITEM_TYPE_CPU_IRQ = 8,
    DASHBOARD_ITEM_TYPE_CPU_SOFT_IRQ = 9,
    DASHBOARD_ITEM_TYPE_CPU_STEAL = 10,
    DASHBOARD_ITEM_TYPE_CPU_GUEST = 11,
    DASHBOARD_ITEM_TYPE_CPU_GUEST_NICE = 12,
    // MEMORY
    DASHBOARD_ITEM_TYPE_MEM_ACTIVE = 13,
    DASHBOARD_ITEM_TYPE_MEM_AVAILABLE = 14,
    DASHBOARD_ITEM_TYPE_MEM_BUFFERED = 15,
    DASHBOARD_ITEM_TYPE_MEM_CACHED = 16,
    DASHBOARD_ITEM_TYPE_MEM_DIRTY = 17,
    DASHBOARD_ITEM_TYPE_MEM_FREE = 18,
    DASHBOARD_ITEM_TYPE_MEM_INACTIVE = 19,
    DASHBOARD_ITEM_TYPE_MEM_LAUNDRY = 20,
    DASHBOARD_ITEM_TYPE_MEM_MAPPED = 21,
    DASHBOARD_ITEM_TYPE_MEM_SHARED = 22,
    DASHBOARD_ITEM_TYPE_MEM_SWAP_CACHED = 23,
    DASHBOARD_ITEM_TYPE_MEM_SWAP_FREE = 24,
    DASHBOARD_ITEM_TYPE_MEM_USED = 25,
    // CPU TEMPERATURE
    DASHBOARD_ITEM_TYPE_CPU_TEMPERATURE = 26,
    // NETWORKING
    DASHBOARD_ITEM_TYPE_NETWORK_INTERFACE_DOWNLOAD_BANDWIDTH = 27,
    DASHBOARD_ITEM_TYPE_NETWORK_INTERFACE_UPLOAD_BANDWIDTH = 28,
    DASHBOARD_ITEM_TYPE_NETWORK_INTERFACE_DOWNLOAD_DYNAMIC_BANDWIDTH = 29,
    DASHBOARD_ITEM_TYPE_NETWORK_INTERFACE_UPLOAD_DYNAMIC_BANDWIDTH = 30,
};

extern const char *DASHBOARD_ITEM_TYPE_LABEL[];

#endif // ESP32_SERVER_DASHBOARD_ITEM_TYPE_H
