#ifndef ESP32_SERVER_DASHBOARD_SCREEN_TYPES_H
#define ESP32_SERVER_DASHBOARD_SCREEN_TYPES_H

enum ScreenType
{
    ST_NONE,
    ST_INFO,       // STATUS INFO SCREEN
    ST_DATA_RESUME // MAIN DASHBOARD DATA RESUME
};

#endif
