#ifndef ESP32_SERVER_DASHBOARD_SCREEN_TYPE_H
#define ESP32_SERVER_DASHBOARD_SCREEN_TYPE_H

enum SCREEN_TYPE
{
    SCREEN_TYPE_NONE = 0,
    SCREEN_TYPE_INFO = 1,                      // STATUS INFO SCREEN
    SCREEN_TYPE_DASHBOARD_REALTIME_GRAPHS = 2, //  DASHBOARD REALTIME GRAPHS SCREEN
};

#endif // ESP32_SERVER_DASHBOARD_SCREEN_TYPE_H
