#ifndef ESP32_SERVER_DASHBOARD_SCREEN_TYPE_H
#define ESP32_SERVER_DASHBOARD_SCREEN_TYPE_H

enum ScreenType
{
    ST_NONE = 0,
    ST_INFO = 1,       // STATUS INFO SCREEN
    ST_DATA_RESUME = 2 // MAIN DASHBOARD DATA RESUME
};

#endif // ESP32_SERVER_DASHBOARD_SCREEN_TYPE_H
