#ifndef ESP32_SERVER_DASHBOARD_SOURCE_INTERFACE_H
#define ESP32_SERVER_DASHBOARD_SOURCE_INTERFACE_H

class ISource
{
public:
    virtual ~ISource() {}
};

#endif // ESP32_SERVER_DASHBOARD_SOURCE_INTERFACE_H
