#ifndef ESP32_SERVER_DASHBOARD_METER_ENTITY_H
#define ESP32_SERVER_DASHBOARD_METER_ENTITY_H

enum MeterEntity
{
    METER_ENTITY_CPU_LOAD,
    METER_ENTITY_MEMORY,
    METER_ENTITY_CPU_TEMPERATURE,
    METER_ENTITY_NETWORK_BANDWITH_DOWNLOAD,
    METER_ENTITY_NETWORK_BANDWITH_UPLOAD
};

#endif
