#ifndef ESP32_SERVER_DASHBOARD_COMMON_DEFINES_H
#define ESP32_SERVER_DASHBOARD_COMMON_DEFINES_H

#define ESP32_SERVER_DASHBOARD_CURRENT_VERSION "0.1alpha"
#define ESP32_SERVER_DASHBOARD_CURRENT_VERSION_DATE "202x/xx/xx"

#endif
