#ifndef ESP32_SERVER_DASHBOARD_COMMON_DEFINES_H
#define ESP32_SERVER_DASHBOARD_COMMON_DEFINES_H

#define ESP32_SERVER_DASHBOARD_CURRENT_VERSION "2.0.0"
#define ESP32_SERVER_DASHBOARD_CURRENT_VERSION_DATE "2024/09/16"

#endif // ESP32_SERVER_DASHBOARD_COMMON_DEFINES_H
