#ifndef ESP32_SERVER_DASHBOARD_METER_ENTITY_H
#define ESP32_SERVER_DASHBOARD_METER_ENTITY_H

enum EntityType
{
    ET_CPU_LOAD,
    ET_USED_MEMORY,
    ET_GLOBAL_CPU_TEMPERATURE,
    ET_NETWORK_BANDWITH_DOWNLOAD_SPEED,
    ET_NETWORK_BANDWITH_UPLOAD_SPEED
};

#endif
